// examples/nextjs-fhe-integration/src/components/fhe/EncryptionDemo.tsx
'use client';

import { useState } from 'react';
import { useFHE } from './FHEProvider';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';

export function EncryptionDemo() {
  const { client, isInitialized } = useFHE();
  const [value, setValue] = useState('');
  const [type, setType] = useState('uint32');
  const [encrypted, setEncrypted] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleEncrypt = async () => {
    if (!client || !value) return;

    setLoading(true);
    try {
      const result = await fetch('/api/fhe/encrypt', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          value: parseInt(value),
          type,
          contractAddress: '0x0000000000000000000000000000000000000000'
        })
      });

      const data = await result.json();
      if (data.success) {
        setEncrypted(JSON.stringify(data.encrypted, null, 2));
      }
    } catch (error) {
      console.error('Encryption error:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card title="Encryption Demo">
      <div className="space-y-4">
        {!isInitialized && (
          <div className="p-4 bg-yellow-900/30 border border-yellow-600 rounded-lg">
            <p className="text-yellow-200">Initializing FHE client...</p>
          </div>
        )}

        <div>
          <label className="block text-sm font-medium mb-2">Value to Encrypt</label>
          <Input
            type="number"
            value={value}
            onChange={(e) => setValue(e.target.value)}
            placeholder="Enter a number"
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">Data Type</label>
          <select
            value={type}
            onChange={(e) => setType(e.target.value)}
            className="w-full px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="uint8">uint8</option>
            <option value="uint16">uint16</option>
            <option value="uint32">uint32</option>
            <option value="uint64">uint64</option>
            <option value="uint128">uint128</option>
            <option value="uint256">uint256</option>
          </select>
        </div>

        <Button
          onClick={handleEncrypt}
          disabled={!isInitialized || !value || loading}
          fullWidth
        >
          {loading ? 'Encrypting...' : 'Encrypt Value'}
        </Button>

        {encrypted && (
          <div className="mt-4">
            <label className="block text-sm font-medium mb-2">Encrypted Result</label>
            <pre className="p-4 bg-gray-800 rounded-lg overflow-x-auto text-sm">
              {encrypted}
            </pre>
          </div>
        )}
      </div>
    </Card>
  );
}

// templates/vue/src/components/EncryptionDemo.vue
<template>
  <div class="card">
    <h2>Encryption Demo</h2>

    <div class="form-group">
      <label>Contract Address</label>
      <input
        type="text"
        v-model="contractAddress"
        placeholder="0x..."
      />
    </div>

    <div class="form-group">
      <label>Value to Encrypt (uint32)</label>
      <input
        type="number"
        v-model="value"
        placeholder="Enter a number"
      />
    </div>

    <button
      @click="handleEncrypt"
      :disabled="!value || isEncrypting"
      class="primary"
    >
      {{ isEncrypting ? 'Encrypting...' : 'Encrypt Value' }}
    </button>

    <div v-if="encryptedData" class="result">
      <h3>Encrypted Result:</h3>
      <pre>{{ encryptedData }}</pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { FhevmClient } from '@fhevm-toolkit/sdk';

const props = defineProps<{
  client: FhevmClient | null;
}>();

const value = ref('');
const contractAddress = ref('0x0000000000000000000000000000000000000000');
const encryptedData = ref<string>('');
const isEncrypting = ref(false);

const handleEncrypt = async () => {
  if (!props.client || !value.value) return;

  try {
    isEncrypting.value = true;
    const result = await props.client.encryptInput({
      value: parseInt(value.value),
      type: 'uint32',
      contractAddress: contractAddress.value,
    });

    encryptedData.value = JSON.stringify(result, null, 2);
  } catch (err) {
    console.error('Encryption error:', err);
    alert('Encryption failed: ' + (err instanceof Error ? err.message : 'Unknown error'));
  } finally {
    isEncrypting.value = false;
  }
};
</script>

<style scoped>
.card {
  background: white;
  border-radius: 8px;
  padding: 2rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.card h2 {
  margin-bottom: 1.5rem;
  font-size: 1.8rem;
}

.form-group {
  margin-bottom: 1.5rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: #374151;
}

.form-group input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 1rem;
}

.form-group input:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

button.primary {
  background: #3b82f6;
  color: white;
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 6px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

button.primary:hover:not(:disabled) {
  background: #2563eb;
}

button.primary:disabled {
  background: #9ca3af;
  cursor: not-allowed;
}

.result {
  margin-top: 1.5rem;
  padding: 1rem;
  background: #f3f4f6;
  border-radius: 6px;
}

.result h3 {
  margin-bottom: 0.75rem;
  font-size: 1.1rem;
}

.result pre {
  background: #1f2937;
  color: #f9fafb;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.875rem;
}
</style>
