// templates/vue/src/components/EncryptionDemo.vue
<template>
  <div class="card">
    <h2>Encryption Demo</h2>

    <div class="form-group">
      <label>Contract Address</label>
      <input
        type="text"
        v-model="contractAddress"
        placeholder="0x..."
      />
    </div>

    <div class="form-group">
      <label>Value to Encrypt (uint32)</label>
      <input
        type="number"
        v-model="value"
        placeholder="Enter a number"
      />
    </div>

    <button
      @click="handleEncrypt"
      :disabled="!value || isEncrypting"
      class="primary"
    >
      {{ isEncrypting ? 'Encrypting...' : 'Encrypt Value' }}
    </button>

    <div v-if="encryptedData" class="result">
      <h3>Encrypted Result:</h3>
      <pre>{{ encryptedData }}</pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { FhevmClient } from '@fhevm-toolkit/sdk';

const props = defineProps<{
  client: FhevmClient | null;
}>();

const value = ref('');
const contractAddress = ref('0x0000000000000000000000000000000000000000');
const encryptedData = ref<string>('');
const isEncrypting = ref(false);

const handleEncrypt = async () => {
  if (!props.client || !value.value) return;

  try {
    isEncrypting.value = true;
    const result = await props.client.encryptInput({
      value: parseInt(value.value),
      type: 'uint32',
      contractAddress: contractAddress.value,
    });

    encryptedData.value = JSON.stringify(result, null, 2);
  } catch (err) {
    console.error('Encryption error:', err);
    alert('Encryption failed: ' + (err instanceof Error ? err.message : 'Unknown error'));
  } finally {
    isEncrypting.value = false;
  }
};
</script>

<style scoped>
.card {
  background: white;
  border-radius: 8px;
  padding: 2rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.card h2 {
  margin-bottom: 1.5rem;
  font-size: 1.8rem;
}

.form-group {
  margin-bottom: 1.5rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: #374151;
}

.form-group input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 1rem;
}

.form-group input:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

button.primary {
  background: #3b82f6;
  color: white;
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 6px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

button.primary:hover:not(:disabled) {
  background: #2563eb;
}

button.primary:disabled {
  background: #9ca3af;
  cursor: not-allowed;
}

.result {
  margin-top: 1.5rem;
  padding: 1rem;
  background: #f3f4f6;
  border-radius: 6px;
}

.result h3 {
  margin-bottom: 0.75rem;
  font-size: 1.1rem;
}

.result pre {
  background: #1f2937;
  color: #f9fafb;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.875rem;
}
</style>

// templates/nextjs/src/components/fhe/EncryptionDemo.tsx
'use client';

import { useState } from 'react';
import { useFHE } from './FHEProvider';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Card } from '@/components/ui/Card';

export const EncryptionDemo = () => {
  const { client, isInitialized, error, init } = useFHE();
  const [value, setValue] = useState('');
  const [encryptedData, setEncryptedData] = useState<string>('');
  const [isEncrypting, setIsEncrypting] = useState(false);
  const [contractAddress, setContractAddress] = useState('0x0000000000000000000000000000000000000000');

  const handleEncrypt = async () => {
    if (!client || !value) return;

    try {
      setIsEncrypting(true);
      const result = await client.encryptInput({
        value: parseInt(value),
        type: 'uint32',
        contractAddress,
      });

      setEncryptedData(JSON.stringify(result, null, 2));
    } catch (err) {
      console.error('Encryption error:', err);
      alert('Encryption failed: ' + (err instanceof Error ? err.message : 'Unknown error'));
    } finally {
      setIsEncrypting(false);
    }
  };

  if (error) {
    return (
      <Card>
        <div className="text-red-600 mb-4">Error: {error}</div>
        <Button onClick={init}>Retry Initialization</Button>
      </Card>
    );
  }

  if (!isInitialized) {
    return (
      <Card>
        <h2 className="text-2xl font-bold mb-4">Initialize FHE Client</h2>
        <p className="mb-4 text-gray-600">
          Connect your wallet to initialize the FHE client and start encrypting data.
        </p>
        <Button onClick={init}>Connect & Initialize</Button>
      </Card>
    );
  }

  return (
    <Card>
      <h2 className="text-2xl font-bold mb-6">Encryption Demo</h2>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Contract Address
          </label>
          <Input
            type="text"
            value={contractAddress}
            onChange={(e) => setContractAddress(e.target.value)}
            placeholder="0x..."
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Value to Encrypt (uint32)
          </label>
          <Input
            type="number"
            value={value}
            onChange={(e) => setValue(e.target.value)}
            placeholder="Enter a number"
          />
        </div>

        <Button onClick={handleEncrypt} disabled={!value || isEncrypting}>
          {isEncrypting ? 'Encrypting...' : 'Encrypt Value'}
        </Button>

        {encryptedData && (
          <div className="mt-6">
            <h3 className="font-semibold mb-2">Encrypted Result:</h3>
            <pre className="bg-gray-100 p-4 rounded overflow-x-auto text-sm">
              {encryptedData}
            </pre>
          </div>
        )}
      </div>
    </Card>
  );
};
